// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqY78ndX8KzztApgDVG1srcN-B_ZAgr0s',
    appId: '1:825177292740:web:9818b92012ca847574ee91',
    messagingSenderId: '825177292740',
    projectId: 'flusix',
    authDomain: 'flusix.firebaseapp.com',
    storageBucket: 'flusix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOkQ5MovFze-k3Ciu8MIRqVMrf3q55-RQ',
    appId: '1:825177292740:android:358184b883b5131c74ee91',
    messagingSenderId: '825177292740',
    projectId: 'flusix',
    storageBucket: 'flusix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxyr0UO6SD_EKJtDXuJJTx-3X_-lsmmVw',
    appId: '1:825177292740:ios:6a76a3215374b15b74ee91',
    messagingSenderId: '825177292740',
    projectId: 'flusix',
    storageBucket: 'flusix.appspot.com',
    iosBundleId: 'com.example.flusix',
  );
}
